/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BLAsignatura;
import BL.BLDocente;
import BL.BLGrado;
import clases.Asignatura;
import clases.Docente;
import clases.Grado;
import clases.Paralelo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexis Montoya
 */
public class CrearAsignaturas extends javax.swing.JFrame {

    /**
     * Creates new form CrearAsignatura
     */
    BLAsignatura blasig = new BLAsignatura();
    Asignatura asig = new Asignatura();
    BLDocente bldoc = new BLDocente();
    Docente doc = new Docente();
    BLGrado blgra = new BLGrado();
    Grado grado = new Grado();

    public CrearAsignaturas() throws ClassNotFoundException, SQLException {
        initComponents();
        ListarGrados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombre_asig = new javax.swing.JTextField();
        boxasig = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtceldoc = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnlimpiar_asig = new javax.swing.JButton();
        btnvolver_asig = new javax.swing.JButton();
        btnguar_asig = new javax.swing.JButton();
        btnlist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Crear Asignatura");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre asignatura: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Grado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        txtnombre_asig.setBackground(new java.awt.Color(0, 0, 0));
        txtnombre_asig.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre_asig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombre_asigKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre_asig, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 100, -1));

        boxasig.setBackground(new java.awt.Color(0, 0, 0));
        boxasig.setForeground(new java.awt.Color(255, 255, 255));
        boxasig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        getContentPane().add(boxasig, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Asignaturas Creadas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cedula Docente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Horario:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtceldoc.setBackground(new java.awt.Color(0, 0, 0));
        txtceldoc.setForeground(new java.awt.Color(255, 255, 255));
        txtceldoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtceldocKeyTyped(evt);
            }
        });
        getContentPane().add(txtceldoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "07:00-08:00", "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00", "12:00-13:00", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnlimpiar_asig.setBackground(new java.awt.Color(102, 102, 102));
        btnlimpiar_asig.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnlimpiar_asig.setText("Limpiar");
        btnlimpiar_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiar_asigActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpiar_asig);

        btnvolver_asig.setBackground(new java.awt.Color(102, 102, 102));
        btnvolver_asig.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnvolver_asig.setText("Volver");
        btnvolver_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolver_asigActionPerformed(evt);
            }
        });
        jPanel1.add(btnvolver_asig);

        btnguar_asig.setBackground(new java.awt.Color(102, 102, 102));
        btnguar_asig.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnguar_asig.setText("Guardar");
        btnguar_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguar_asigActionPerformed(evt);
            }
        });
        jPanel1.add(btnguar_asig);

        btnlist.setBackground(new java.awt.Color(102, 102, 102));
        btnlist.setText("Cargar Asignaturas");
        btnlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistActionPerformed(evt);
            }
        });
        jPanel1.add(btnlist);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 360, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 250, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolver_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolver_asigActionPerformed
        // TODO add your handling code here:
        GUISecretaria secre = new GUISecretaria();
        secre.setEnabled(true);
        secre.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvolver_asigActionPerformed

    private void btnguar_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguar_asigActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            crearAsigatura();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearGrado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrearGrado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnguar_asigActionPerformed

    private void btnlimpiar_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiar_asigActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnlimpiar_asigActionPerformed

    private void btnlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ListarDatos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearGrado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrearGrado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnlistActionPerformed

    private void txtnombre_asigKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombre_asigKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingrese solo letras");
        }
        if (Character.isLowerCase(validar)) {
            String cad = ("" + validar).toUpperCase();
            validar = cad.charAt(0);
            evt.setKeyChar(validar);
        }
    }//GEN-LAST:event_txtnombre_asigKeyTyped

    private void txtceldocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtceldocKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingrese solo numeros");
        }
    }//GEN-LAST:event_txtceldocKeyTyped

    /**
     * @param args the command line arguments
     */
    public void ListarDatos() throws ClassNotFoundException, SQLException {
        //Como el método de la BL retorna un ArrayList de la clase Estudiantes
        //Aqui lo recuperamos

        ArrayList<Asignatura> lstdocentes = blasig.ConsultaLista();

        Object columnas[] = {"Asignatura", "Horario", "Grado", "Docente"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);

        for (Asignatura objeto : lstdocentes) {
            //String id=String.valueOf(objeto.getStrCodigo());
            String nombres = objeto.getNombre();
            String horario = objeto.getHorario();
            int docente = objeto.getDocente().getCodigoCarnet();
            int grado = objeto.getGrado().getId();
            String modeloTemp[] = {nombres, horario, String.valueOf(docente), String.valueOf(grado)};
            modelo.addRow(modeloTemp);
        }

    }

    private void limpiar() {
        this.txtceldoc.setText("");

    }

    public boolean validar() {
        if (txtceldoc.getText().equals("") && txtnombre_asig.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "campo de texto   estan vacio", "Asignatura", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        try {
            return true;
        } catch (NullPointerException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "algun dato esta con el formato incorrecto", "Asignatura", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }

    }

    private void crearAsigatura() throws ClassNotFoundException, SQLException {
        String cedula = this.txtceldoc.getText();
        doc.setCedula(cedula);
        int x = 0;
        System.out.println(doc);
        try {
            System.out.println("ola");
            x = bldoc.Consultar_id(doc);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearAsignatura.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrearAsignatura.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(x);
        if (validar()) {
            int grados = this.boxasig.getSelectedIndex();
            String horario = (String) this.jComboBox1.getSelectedItem();
            grado.setId(grados);
            System.out.println(grado);
            doc.setCodigoCarnet(x);
            asig.setNombre(this.txtnombre_asig.getText());
            asig.setGrado(grado);
            asig.setDocente(doc);
            asig.setHorario(horario);
            if (blasig.Consultar(asig)) {
                boolean creado = blasig.RegistrarAsignatura(asig);
                if (creado) {
                    limpiar();
                    this.ListarDatos();
                    JOptionPane.showMessageDialog(this, "Se creo la Asignatura", "Crear Asignatura", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo Crear la Asignatura", "crear asignatura", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "La asignatura ya existe", "Crear asignatura", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    public void ListarGrados() throws ClassNotFoundException, SQLException {
        ArrayList<Grado> lstAsignaturas = new ArrayList<>();

        lstAsignaturas = blgra.ConsultaLista3();
        DefaultComboBoxModel dlm = new DefaultComboBoxModel();
        Grado objp = new Grado("seleccione", new Paralelo("paralelo"));
        dlm.addElement(objp);
        for (Grado p : lstAsignaturas) {
            dlm.addElement(p);
        }
        this.boxasig.setModel(dlm);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CrearAsignaturas().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CrearAsignatura.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CrearAsignatura.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxasig;
    private javax.swing.JButton btnguar_asig;
    private javax.swing.JButton btnlimpiar_asig;
    private javax.swing.JButton btnlist;
    private javax.swing.JButton btnvolver_asig;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtceldoc;
    private javax.swing.JTextField txtnombre_asig;
    // End of variables declaration//GEN-END:variables
}
