/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BLAlumno;
import BL.BLGrado;
import BL.BLRepresentante;
import BL.Expresiones;
import Data.DataGrado;
import Data.DataRepresentante;
import clases.Estudiante;
import clases.Grado;
import clases.Representante;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class CrearAlumno extends javax.swing.JFrame {

    BLAlumno blalumno = new BLAlumno();
    Estudiante alumno = new Estudiante();
    Expresiones expre = new Expresiones();

    public CrearAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombreDocente = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabelTelefonoDocente = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jLabelRhDocente = new javax.swing.JLabel();
        jLabelCCTIDocente = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jLabelEdadDocente = new javax.swing.JLabel();
        jLabelApellidoDocente = new javax.swing.JLabel();
        jTextApellidp = new javax.swing.JTextField();
        jLabelAsignatura2 = new javax.swing.JLabel();
        jTextedita = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButtonVolverDocente = new javax.swing.JButton();
        jButtonLimpiarDocente = new javax.swing.JButton();
        jButtonAceptarDocente = new javax.swing.JButton();
        jButtonModificarEstu = new javax.swing.JButton();
        jButtonEliminarestu = new javax.swing.JButton();
        jButtonCargarEstu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTexteditdirec = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Crear Alumno");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 170, -1));

        jLabelNombreDocente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNombreDocente.setText("Nombre:");
        jPanel1.add(jLabelNombreDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTextNombre.setBackground(new java.awt.Color(0, 0, 0));
        jTextNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, -1));

        jLabelTelefonoDocente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTelefonoDocente.setText("Telefono:");
        jPanel1.add(jLabelTelefonoDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jTextTelefono.setBackground(new java.awt.Color(0, 0, 0));
        jTextTelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jTextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, -1));

        jTextDireccion.setBackground(new java.awt.Color(0, 0, 0));
        jTextDireccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, -1));

        jLabelRhDocente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRhDocente.setText("Direccion:");
        jPanel1.add(jLabelRhDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabelCCTIDocente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCCTIDocente.setText("Cedula:");
        jPanel1.add(jLabelCCTIDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextCedula.setBackground(new java.awt.Color(0, 0, 0));
        jTextCedula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextCedula.setForeground(new java.awt.Color(255, 255, 255));
        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulaActionPerformed(evt);
            }
        });
        jTextCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCedulaKeyTyped(evt);
            }
        });
        jPanel1.add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, -1));

        jLabelEdadDocente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEdadDocente.setText("Edad:");
        jPanel1.add(jLabelEdadDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabelApellidoDocente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelApellidoDocente.setText("Apellido:");
        jPanel1.add(jLabelApellidoDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jTextApellidp.setBackground(new java.awt.Color(0, 0, 0));
        jTextApellidp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextApellidp.setForeground(new java.awt.Color(255, 255, 255));
        jTextApellidp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApellidpKeyTyped(evt);
            }
        });
        jPanel1.add(jTextApellidp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 150, -1));

        jLabelAsignatura2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAsignatura2.setText("Seleccione un estudiante:");
        jPanel1.add(jLabelAsignatura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jTextedita.setBackground(new java.awt.Color(0, 0, 0));
        jTextedita.setForeground(new java.awt.Color(255, 255, 255));
        jTextedita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexteditaKeyTyped(evt);
            }
        });
        jPanel1.add(jTextedita, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 170, -1));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 330, 160));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(6, 6, 14, 1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonVolverDocente.setBackground(new java.awt.Color(102, 102, 102));
        jButtonVolverDocente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonVolverDocente.setText("Volver");
        jButtonVolverDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverDocenteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVolverDocente);

        jButtonLimpiarDocente.setBackground(new java.awt.Color(102, 102, 102));
        jButtonLimpiarDocente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonLimpiarDocente.setText("Limpiar");
        jButtonLimpiarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarDocenteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLimpiarDocente);

        jButtonAceptarDocente.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAceptarDocente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAceptarDocente.setText("Guardar");
        jButtonAceptarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarDocenteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAceptarDocente);

        jButtonModificarEstu.setBackground(new java.awt.Color(102, 102, 102));
        jButtonModificarEstu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonModificarEstu.setText("Modificar Alumno");
        jButtonModificarEstu.setEnabled(false);
        jButtonModificarEstu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEstuActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonModificarEstu);

        jButtonEliminarestu.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEliminarestu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEliminarestu.setText("Eliminar Alumno");
        jButtonEliminarestu.setEnabled(false);
        jButtonEliminarestu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarestu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarestuActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEliminarestu);

        jButtonCargarEstu.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCargarEstu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCargarEstu.setText("Cargar Alumnos");
        jButtonCargarEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarEstuActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCargarEstu);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 610, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cambiar direccion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jTexteditdirec.setBackground(new java.awt.Color(0, 0, 0));
        jTexteditdirec.setForeground(new java.awt.Color(255, 255, 255));
        jTexteditdirec.setEnabled(false);
        jPanel1.add(jTexteditdirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 160, -1));

        jButton2.setText("Si");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jButton3.setText("No");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 714, 444));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void habilitarComponentes() {
        jButtonEliminarestu.setEnabled(false);
        jButtonModificarEstu.setEnabled(false);
        jButtonAceptarDocente.setEnabled(true);
        jButtonLimpiarDocente.setEnabled(true);
        jButtonCargarEstu.setEnabled(true);

    }

    public void ListarDatos() throws ClassNotFoundException, SQLException {
        //Como el método de la BL retorna un ArrayList de la clase Estudiantes
        //Aqui lo recuperamos

        ArrayList<Estudiante> lstestudiante = blalumno.ConsultaLista();

        Object columnas[] = {"nombres", "apellidos", "edad", "cedula", "direccion", "Telefono"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);

        for (Estudiante objeto : lstestudiante) {
            //String id=String.valueOf(objeto.getStrCodigo());
            String nombres = objeto.getNombre();
            String apellidos = objeto.getApellido();
            String direccion = objeto.getDireccion();
            String cedula = objeto.getCedula();
            int edad = objeto.getEdad();
            String telefono = objeto.getTelefono();
            System.out.println(nombres + apellidos + edad + cedula + direccion + telefono);
            String modeloTemp[] = {nombres, apellidos, String.valueOf(edad), cedula, direccion, telefono};
            modelo.addRow(modeloTemp);
        }

    }

    private void limpiar() {
        this.jTextNombre.setText("");
        this.jTextApellidp.setText("");
        this.jTextTelefono.setText("");
        this.jTextDireccion.setText("");
        this.jTextCedula.setText("");
        this.jTextedita.setText("");
        this.jTexteditdirec.setText("");

        habilitarComponentes();
    }

    public boolean validar() {
        if (jTextNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "campo de texto del nombre del alumno esta vacio", "estudiante", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (jTextApellidp.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "campo de texto del apellido del alumno esta vacio", "estudiante", JOptionPane.INFORMATION_MESSAGE);
            return false;

        } else if (jTextCedula.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "campo de texto del documento del alumno esta vacio", "estudiante", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (jTextTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "campo de texto del telefono del alumno esta vacio", "estudiante", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (jTextDireccion.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "campo de texto del RH del alumno esta vacio", "estudiante", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else {
            try {
                Integer.parseInt(jTextCedula.getText());
                return true;
            } catch (NullPointerException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "algun dato esta con el formato incorrecto", "estudiante", JOptionPane.INFORMATION_MESSAGE);
                return false;
            }

        }
    }

    private void crearEstudiante() throws ClassNotFoundException, SQLException {
        boolean creado = false;
        if (validar()) {

            alumno.setCedula(String.valueOf(jTextCedula.getText()));
            alumno.setTelefono(String.valueOf(jTextTelefono.getText()));
            alumno.setNombre(jTextNombre.getText());
            alumno.setApellido(jTextApellidp.getText());
            alumno.setDireccion(jTextDireccion.getText());
            alumno.setEdad((int) this.jSpinner1.getValue());

            if (blalumno.Consultar(alumno)) {
                if (expre.calle(jTextDireccion.getText()) && expre.NumeroTelefono(jTextTelefono.getText())) {
                    creado = blalumno.RegistrarEstudiante(alumno);
                } else {
                    JOptionPane.showMessageDialog(this, "direccion o numero incorectos", "Crear estudiante", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                }
                if (creado) {
                    limpiar();
                    this.ListarDatos();
                    JOptionPane.showMessageDialog(this, "Se creo el alumno", "Crear estudiante", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo Crear el alumno", "crear estudiante", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                jTextCedula.setText("");
                jTextCedula.requestFocus();
                JOptionPane.showMessageDialog(this, "El alumno ya existe", "Crear alumno", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private void eliminarEstudiante() throws SQLException, ClassNotFoundException {

        String cedula = this.jTextedita.getText();
        alumno.setCedula(cedula);
        if (blalumno.Consultar(alumno)) {
            blalumno.Eliminar(alumno);
            JOptionPane.showMessageDialog(this, "se elimino el estudiante", "estudiantes", JOptionPane.INFORMATION_MESSAGE);
            habilitarComponentes();
            this.ListarDatos();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "estudiante no existe", "estudiantes", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void modificarEstudiante() throws ClassNotFoundException, SQLException {

        String Direccion = this.jTexteditdirec.getText();
        String Cedula = this.jTextedita.getText();
        alumno.setCedula(Cedula);

        if (blalumno.Consultar(alumno)) {
            
            alumno.setDireccion(Direccion);
            blalumno.Modificar(alumno);
            JOptionPane.showMessageDialog(this, "Direccion Modificada", "estudiantes", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "estudiante no existe", "estudiantes", JOptionPane.INFORMATION_MESSAGE);
        }

    }
    private void jButtonAceptarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarDocenteActionPerformed

        try {
            crearEstudiante();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearAlumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrearAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonAceptarDocenteActionPerformed

    private void jButtonLimpiarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarDocenteActionPerformed
        limpiar();
        jTextCedula.setEditable(true);
    }//GEN-LAST:event_jButtonLimpiarDocenteActionPerformed

    private void jButtonVolverDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverDocenteActionPerformed
        GUISecretaria secre = new GUISecretaria();
        secre.setEnabled(true);
        secre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverDocenteActionPerformed

    private void jButtonCargarEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarEstuActionPerformed
        try {
            this.ListarDatos();
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());

        }
    }//GEN-LAST:event_jButtonCargarEstuActionPerformed

    private void jButtonModificarEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEstuActionPerformed
        try {
            modificarEstudiante();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearAlumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrearAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar();
    }//GEN-LAST:event_jButtonModificarEstuActionPerformed

    private void jButtonEliminarestuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarestuActionPerformed
        try {
            eliminarEstudiante();
        } catch (SQLException ex) {
            Logger.getLogger(CrearDocente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar();
    }//GEN-LAST:event_jButtonEliminarestuActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingrese solo letras");
        }
        if (Character.isLowerCase(validar)) {
            String cad = ("" + validar).toUpperCase();
            validar = cad.charAt(0);
            evt.setKeyChar(validar);
        }
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextApellidpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellidpKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingrese solo letras");
        }
        if (Character.isLowerCase(validar)) {
            String cad = ("" + validar).toUpperCase();
            validar = cad.charAt(0);
            evt.setKeyChar(validar);
        }
    }//GEN-LAST:event_jTextApellidpKeyTyped

    private void jTextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefonoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingrese solo numeros");
        }

    }//GEN-LAST:event_jTextTelefonoKeyTyped

    private void jTextCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCedulaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingrese solo numeros");
        }

    }//GEN-LAST:event_jTextCedulaKeyTyped

    private void jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTexteditdirec.setEnabled(true);
        this.jButtonModificarEstu.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jButton2.setEnabled(true);
        this.jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.jButtonEliminarestu.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTexteditaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexteditaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingrese CEDULA a eliminar");
        }
    }//GEN-LAST:event_jTexteditaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAceptarDocente;
    private javax.swing.JButton jButtonCargarEstu;
    private javax.swing.JButton jButtonEliminarestu;
    private javax.swing.JButton jButtonLimpiarDocente;
    private javax.swing.JButton jButtonModificarEstu;
    private javax.swing.JButton jButtonVolverDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellidoDocente;
    private javax.swing.JLabel jLabelAsignatura2;
    private javax.swing.JLabel jLabelCCTIDocente;
    private javax.swing.JLabel jLabelEdadDocente;
    private javax.swing.JLabel jLabelNombreDocente;
    private javax.swing.JLabel jLabelRhDocente;
    private javax.swing.JLabel jLabelTelefonoDocente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextApellidp;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jTextedita;
    private javax.swing.JTextField jTexteditdirec;
    // End of variables declaration//GEN-END:variables
}
