/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BLAlumno;
import BL.BLNotas;
import clases.Estudiante;
import clases.Nota;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexis Montoya
 */
public class GUINotasEstudiantes extends javax.swing.JFrame {

    Estudiante estu = new Estudiante();
    BLAlumno BLalumno = new BLAlumno();
    Nota notas = new Nota();
    BLNotas BLnotas = new BLNotas();
      ArrayList<Nota> lista = new ArrayList<>();

    int x = 0;
    Object[] columnas = {"idASIg","Parcial1.1", "Parcial1.2", "Parcial1.3", "Quimestre1", "Parcial2.1", "Parcial2.2", "Parcial2.3",
        "Quimestre2", "Nota final"};
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);

    public GUINotasEstudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcedula = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btncargarnot = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NOTAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cedula Estudiante:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jcedula.setBackground(new java.awt.Color(0, 0, 0));
        jcedula.setForeground(new java.awt.Color(255, 255, 255));
        jcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcedulaKeyTyped(evt);
            }
        });
        getContentPane().add(jcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 114, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 430, 140));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btncargarnot.setBackground(new java.awt.Color(102, 102, 102));
        btncargarnot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btncargarnot.setText("Cargar Notas");
        btncargarnot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarnotActionPerformed(evt);
            }
        });
        jPanel1.add(btncargarnot);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        btnSalir.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 300, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Listar() throws ClassNotFoundException, SQLException{
         estu.setCedula(this.jcedula.getText());
        try {
            x = BLalumno.Consultar_id(estu);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUINotasEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUINotasEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        estu.setCodigoCarnet(x);
              this.jTable1.removeAll();
       
            lista = BLnotas.Consultares(estu);
       
        // añade los objetos a la tabla
        this.jTable1.setModel(modelo);
        for (Nota Objestu : lista) {
            String NewValor[] = {
                String.valueOf(Objestu.getAsignaturas().getIdasig()),
                String.valueOf(Objestu.getPar11()),
                String.valueOf(Objestu.getPar12()),
                String.valueOf(Objestu.getPar13()),
                String.valueOf(Objestu.getQuimestre1()),
                String.valueOf(Objestu.getPar21()),
                String.valueOf(Objestu.getPar22()),
                String.valueOf(Objestu.getPar23()),
                String.valueOf(Objestu.getQuimestre2()),
                String.valueOf(Objestu.getNotaFinal()),
            };
            modelo.addRow(NewValor);
        };
        

       
    }
    private void btncargarnotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarnotActionPerformed
        try {
            // TODO add your handling code here:
            Listar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUINotasEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUINotasEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btncargarnotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         GUISecretaria secre = new GUISecretaria();
                secre.setEnabled(true);
                secre.setVisible(true);
                dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         InicioSecion inicio = new InicioSecion();
                inicio.setEnabled(true);
                inicio.setVisible(true);
                dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcedulaKeyTyped
        // TODO add your handling code here:
          char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "ingrese solo numeros");
        }
    }//GEN-LAST:event_jcedulaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUINotasEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUINotasEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUINotasEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUINotasEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUINotasEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btncargarnot;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jcedula;
    // End of variables declaration//GEN-END:variables
}
